version: '3.9'

services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/mentor.db:/app/mentor.db
    restart: unless-stopped
    environment:
      - CORS_ORIGINS_STR=http://207.154.224.101,http://localhost:3000,http://localhost:5173

  frontend:
    build:
      context: ./frontend
      args:
        - NODE_ENV=production
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - VITE_API_BASE_URL=http://207.154.224.101:8000