version: '3.9'

services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/mentor.db:/app/mentor.db
      - ./logs:/app/logs
    restart: unless-stopped
    environment:
      - CORS_ORIGINS_STR=http://207.154.224.101,https://207.154.224.101
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      args:
        - NODE_ENV=production
        - VITE_API_BASE_URL=http://207.154.224.101:8000
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  logs:
